name: Bulid Mars Buildroot Image (CI Version)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - Name: "Mars"
            Branch: "dev"
          - Name: "Mars CM eMMC"
            Branch: "dev-mars-cm"
          - Name: "Mars CM SD Card"
            Branch: "dev-mars-cm-sdcard"
    runs-on: ubuntu-latest
    name: Build Image for ${{ matrix.Name }}
    continue-on-error: true
    steps:
    
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.Branch }}
        
    - name: Check Commit ID
      id: truecommit
      run: |
        echo "shortid=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        echo "longid=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        echo "$(git log -1)" >> ${{ github.workspace }}/message.log

    - name: Initialization environment
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y build-essential automake libtool texinfo bison flex gawk g++ git xxd curl wget gdisk gperf cpio bc screen texinfo unzip libgmp-dev \libmpfr-dev libmpc-dev libssl-dev libncurses-dev libglib2.0-dev libpixman-1-dev libyaml-dev patchutils python3-pip zlib1g-dev device-tree-compiler dosfstools mtools kpartx rsync

    - name: Make
      run: make -j$(nproc) 2>&1 | tee ${{ github.workspace }}/build.log

    - name: Make Rootfs
      run: make buildroot_rootfs -j$(nproc) 2>&1 | tee ${{ github.workspace }}/rootfs.log

    - name: Make Image
      id: imagegen
      run: make img -j$(nproc) 2>&1 | tee ${{ github.workspace }}/img.log

    - name: Generate Hash
      working-directory: ${{ github.workspace }}/work
      run: |
        echo "$(sha256sum **/**)" >> ${{ github.workspace }}/Mars-Buildroot.sha256

    - name: Upload Log
      uses: actions/upload-artifact@main
      if: ${{ !cancelled() }}
      with:
        name: ${{ matrix.Name }}-${{ steps.truecommit.outputs.shortid }}-Log
        path: |
          ${{ github.workspace }}/*.log
        if-no-files-found: error

    - name: Upload Image
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.Name }}-${{ steps.truecommit.outputs.shortid }}-Image
        path: |
          ${{ github.workspace }}/work/sdcard.img
        if-no-files-found: error
    
    - name: Upload Work Dir
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.Name }}-${{ steps.truecommit.outputs.shortid }}-Work
        path: |
          ${{ github.workspace }}/work/
        if-no-files-found: error
    
    - name: Output Success Summary
      if: steps.imagegen.outcome == 'success'
      run: |
        echo "# Mars Buildroot Image Building Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[CI #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) powered by [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) has successfully built the ${{ matrix.Name }} Buildroot image." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "CI has built on commit [${{ steps.truecommit.outputs.shortid }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.truecommit.outputs.longid }}). The commit message is shown below." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/message.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Artifacts Hash" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/Mars-Buildroot.sha256 >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/build.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Rootfs Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/rootfs.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Image Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/img.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
    
    - name: Output Failed Summary
      if: ${{ !cancelled() && !success() }}
      run: |
        echo "# Vega Buildroot Image Building Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[CI #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) powered by [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) has failed to built the ${{ matrix.Name }} Buildroot image." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "CI has built on commit [${{ steps.truecommit.outputs.shortid }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.truecommit.outputs.longid }}). The commit message is shown below." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/message.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/build.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Rootfs Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/rootfs.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Image Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        tail -100 ${{ github.workspace }}/img.log >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
